name: carnd-advdl-odlab
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.6
    - pip
    - numpy
    - matplotlib
    - jupyter
    - pillow
    - scipy
    - ffmpeg
    # - imageio==2.1.2
    - imageio
    - moviepy
    - pip:
        - tensorflow-gpu==1.4